"""add payment fields

Revision ID: 98f5dd9e5b8f
Revises: 
Create Date: 2025-04-16 17:30:33.825441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98f5dd9e5b8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('language_practice', sa.Column('expiry_date', sa.DateTime(), nullable=True))
    op.add_column('language_practice', sa.Column('request_token', sa.String(length=100), nullable=True))
    op.add_column('language_practice', sa.Column('status', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'language_practice', ['request_token'])
    op.add_column('tour_booking', sa.Column('payment_status', sa.String(length=20), nullable=False))
    op.add_column('tour_booking', sa.Column('total_cost', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tour_booking', 'total_cost')
    op.drop_column('tour_booking', 'payment_status')
    op.drop_constraint(None, 'language_practice', type_='unique')
    op.drop_column('language_practice', 'status')
    op.drop_column('language_practice', 'request_token')
    op.drop_column('language_practice', 'expiry_date')
    # ### end Alembic commands ###
